[package]
org = "ballerinai"
name = "observe"
version = "@toml.version@"
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/observe-internal-native-@project.version@.jar"
