[package]
org = "ballerinai"
name = "observe"
version = "1.3.0"
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/observe-internal-native-1.3.0-SNAPSHOT.jar"
